### ISSUE TITLE
How to apply multiple negative sampling on sampling based method? 

### ISSUE THREAD

**Issue by Weile0409** [chenchongthu/GHCF#5]
Dear author, I would like to ask you how to apply multiple negative sampling on sampling based method? (eg. LightGCN).
I have seen the code, but the number of negative sample = 1, how to set it to 4, as mentioned in your paper? 
Thanks !

**Comment by chenchongthu** [comment]
Hi,

load_data.py,  266-267. You can change the following code to apply multiple negative sampling on sampling-based methods

 pos_items += sample_pos_items_for_u(u, 1)
 neg_items += sample_neg_items_for_u(u, 1)

**Comment by Weile0409** [comment]
Thank you and have a nice day :))
